#!/usr/bin/env ruby

require 'webrick'
#require 'tempfile'

request = WEBrick::HTTPRequest.new(WEBrick::Config::HTTP)
request.parse(STDIN)

File.open("/Users/Shared/bungi/ClayBox.log", "w") {|f|
  f.write(DateTime.now.iso8601 + " ")
  f.write(request.request_method + " ")
  f.write(request.request_uri.to_s)
  f.write("\n");
}

success = true

response = WEBrick::HTTPResponse.new(WEBrick::Config::HTTP)

if success
  response.status = 200 # HTTP OK: Nothing created and we aren't returning a Location
else
  response.status = 500 # Internal Server Error
end

response.content_type = 'text/plain'
response.body = "OK!\n"

STDERR.write response.to_s
