#!/usr/bin/env ruby 

# Might be better to log lines as JSON instead of a HTTP-log like format...

require 'uri'
require 'getoptlong'

$AfterDate = nil
GetoptLong.new(
  [ "--after", "-a", GetoptLong::REQUIRED_ARGUMENT ]
).each do |opt,arg|
  case opt
  when "--after"
    $AfterDate = arg
  else
    usage()
  end
end


log_lines = File.read("/Users/Shared/bungi/ClayBox.log").split(/[\r\n]+/)

print "date,temperature,humidity\n"

log_lines.each {|l|
  components = l.split(/\s+/)
  next if (components.length != 3)

  date = components[0]
  uri = URI(components[2])
  
  parameters = {}
  uri.query.split("&").each {|kv|
    pair = kv.split("=")
    if (pair.count == 2)
      parameters[pair[0]] = pair[1]
    end
  }
  
  next if $AfterDate && $AfterDate > date
    
  temperature = parameters['temperature']
  humidity = parameters['humidity']
  next unless temperature && humidity
  
  print "#{date},#{temperature},#{humidity}\n"
}
